"""WAF detection and bypass testing module."""

from __future__ import annotations

import re
from typing import Any

from pencheff.config import Severity
from pencheff.core.findings import Evidence, Finding
from pencheff.core.http_client import PencheffHTTPClient
from pencheff.core.payload_loader import load_payloads
from pencheff.core.session import PentestSession
from pencheff.modules.base import BaseTestModule

# WAF fingerprints: response patterns that identify specific WAF vendors
WAF_SIGNATURES = {
    "cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "server": ["cloudflare"],
        "body_patterns": ["attention required", "cloudflare ray id", "cloudflare to restrict access"],
        "status_codes": [403, 503],
    },
    "aws_waf": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id"],
        "body_patterns": ["<html><head><title>403 forbidden</title>"],
        "status_codes": [403],
    },
    "akamai": {
        "headers": ["x-akamai-transformed", "akamai-grn"],
        "server": ["akamaighost", "akamai"],
        "body_patterns": ["reference&#32;&#35;", "access denied", "akamai"],
        "status_codes": [403],
    },
    "imperva_incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "body_patterns": ["incapsula incident id", "powered by incapsula", "_incap_"],
        "cookies": ["visid_incap_", "incap_ses_"],
        "status_codes": [403],
    },
    "modsecurity": {
        "server": ["mod_security", "modsecurity"],
        "body_patterns": ["mod_security", "modsecurity", "not acceptable", "method not implemented"],
        "status_codes": [403, 406, 501],
    },
    "f5_big_ip_asm": {
        "headers": ["x-wa-info"],
        "server": ["bigip"],
        "cookies": ["ts", "bigipserver"],
        "body_patterns": ["the requested url was rejected"],
        "status_codes": [403],
    },
    "fortinet_fortiweb": {
        "headers": ["fortiwafsid"],
        "body_patterns": ["fortigate", "fortiweb", ".fgd_icon"],
        "status_codes": [403],
    },
    "sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "server": ["sucuri"],
        "body_patterns": ["sucuri website firewall", "access denied - sucuri"],
        "status_codes": [403],
    },
    "barracuda": {
        "headers": ["barra_counter_session"],
        "body_patterns": ["barracuda", "barra_counter_session"],
        "status_codes": [403],
    },
    "wordfence": {
        "body_patterns": ["wordfence", "your access to this site has been limited", "generated by wordfence"],
        "status_codes": [403, 503],
    },
}

# Trigger payloads guaranteed to trip most WAFs
WAF_TRIGGER_PAYLOADS = [
    "<script>alert(1)</script>",
    "' OR 1=1--",
    "../../etc/passwd",
    "; ls -la",
    "{{7*7}}",
    "${7*7}",
    "<?xml version='1.0'?><!DOCTYPE foo [<!ENTITY xxe SYSTEM 'file:///etc/passwd'>]>",
]


class WAFDetectionModule(BaseTestModule):
    """Detect and fingerprint WAF/IPS, then test bypass techniques."""

    name = "waf_detection"
    category = "waf_bypass"
    owasp_categories = ["A05"]
    description = "WAF detection, fingerprinting, and bypass testing"

    def get_techniques(self) -> list[str]:
        return [
            "waf_fingerprinting",
            "encoding_bypass",
            "unicode_bypass",
            "case_mutation",
            "comment_injection",
            "chunked_bypass",
        ]

    async def run(
        self,
        session: PentestSession,
        http: PencheffHTTPClient,
        targets: list[str] | None = None,
        config: dict[str, Any] | None = None,
    ) -> list[Finding]:
        findings: list[Finding] = []
        base_url = session.target.base_url
        endpoints = self._get_target_endpoints(session, targets)
        test_url = endpoints[0]["url"] if endpoints else base_url

        # Phase 1: Detect WAF presence
        waf_vendor, waf_confidence, waf_evidence = await self._detect_waf(
            http, test_url, session
        )

        if waf_vendor:
            session.discovered.waf_detected = {
                "vendor": waf_vendor,
                "confidence": waf_confidence,
                "bypass_hints": [],
            }
            findings.append(Finding(
                title=f"WAF Detected: {waf_vendor}",
                severity=Severity.INFO,
                category="waf_bypass",
                owasp_category="A05",
                description=(
                    f"A Web Application Firewall ({waf_vendor}) was detected with "
                    f"{waf_confidence}% confidence. This may block certain attack payloads "
                    "but can potentially be bypassed with encoding techniques."
                ),
                remediation="WAF is a defense-in-depth measure. Ensure application-level security is not solely reliant on WAF.",
                endpoint=test_url,
                evidence=waf_evidence,
                cwe_id="CWE-693",
                cvss_score=0.0,
            ))

            # Phase 2: Test bypass techniques
            bypass_findings = await self._test_bypasses(
                http, test_url, waf_vendor, session
            )
            findings.extend(bypass_findings)
        else:
            session.discovered.waf_detected = {"vendor": None, "confidence": 0}

        return findings

    async def _detect_waf(
        self, http: PencheffHTTPClient, url: str, session: PentestSession
    ) -> tuple[str | None, int, list[Evidence]]:
        """Send trigger payloads and fingerprint WAF from responses."""
        evidence_list: list[Evidence] = []
        vendor_scores: dict[str, int] = {v: 0 for v in WAF_SIGNATURES}

        # First get a baseline response
        try:
            baseline = await http.get(url, module="waf_detection")
            baseline_status = baseline.status_code
        except Exception:
            baseline_status = 200

        for payload in WAF_TRIGGER_PAYLOADS:
            test_url = f"{url}?test={payload}"
            try:
                resp = await http.get(test_url, module="waf_detection")
            except Exception:
                continue

            # If we got blocked (different status from baseline), analyze the response
            if resp.status_code != baseline_status and resp.status_code in (403, 406, 429, 501, 503):
                resp_headers = {k.lower(): v.lower() for k, v in resp.headers.items()}
                resp_body = resp.text.lower()[:2000]
                resp_cookies = str(resp.headers.get("set-cookie", "")).lower()

                for vendor, sigs in WAF_SIGNATURES.items():
                    # Check headers
                    for h in sigs.get("headers", []):
                        if h.lower() in resp_headers:
                            vendor_scores[vendor] += 3

                    # Check server header
                    server = resp_headers.get("server", "")
                    for s in sigs.get("server", []):
                        if s.lower() in server:
                            vendor_scores[vendor] += 4

                    # Check body patterns
                    for pattern in sigs.get("body_patterns", []):
                        if pattern.lower() in resp_body:
                            vendor_scores[vendor] += 3

                    # Check cookies
                    for cookie in sigs.get("cookies", []):
                        if cookie.lower() in resp_cookies:
                            vendor_scores[vendor] += 3

                    # Check status codes
                    if resp.status_code in sigs.get("status_codes", []):
                        vendor_scores[vendor] += 1

                evidence_list.append(Evidence(
                    request_method="GET",
                    request_url=test_url,
                    response_status=resp.status_code,
                    response_body_snippet=resp.text[:300],
                    description=f"Trigger payload '{payload}' returned {resp.status_code}",
                ))

        # Determine best match
        best_vendor = max(vendor_scores, key=vendor_scores.get)  # type: ignore[arg-type]
        best_score = vendor_scores[best_vendor]

        if best_score >= 3:
            confidence = min(best_score * 15, 99)
            return best_vendor, confidence, evidence_list

        # Check if any blocking occurred even without vendor match
        if evidence_list:
            return "unknown_waf", 50, evidence_list

        return None, 0, []

    async def _test_bypasses(
        self,
        http: PencheffHTTPClient,
        url: str,
        waf_vendor: str,
        session: PentestSession,
    ) -> list[Finding]:
        """Test WAF bypass techniques."""
        findings: list[Finding] = []
        bypass_payloads = load_payloads("waf_bypass.txt")
        if not bypass_payloads:
            # Fallback inline bypasses
            bypass_payloads = [
                "%3Cscript%3Ealert(1)%3C/script%3E",  # URL encoded
                "%253Cscript%253Ealert(1)%253C%252Fscript%253E",  # Double URL encoded
                "<scr<script>ipt>alert(1)</scr</script>ipt>",  # Nested tags
                "<ScRiPt>alert(1)</ScRiPt>",  # Case variation
                "<script>alert`1`</script>",  # Template literal
                "\\u003cscript\\u003ealert(1)\\u003c/script\\u003e",  # Unicode escape
                "<svg/onload=alert(1)>",  # SVG alternative
                "<img src=x onerror=alert(1)>",  # Event handler
                "' OR/**/ 1=1--",  # SQL comment bypass
                "' /*!OR*/ 1=1--",  # MySQL comment bypass
                "'%20OR%201=1--",  # URL encoded SQL
                "' oR 1=1--",  # Case variation SQL
                "..%2f..%2f..%2fetc%2fpasswd",  # Encoded path traversal
                "..%252f..%252f..%252fetc%252fpasswd",  # Double encoded traversal
                "%00../../etc/passwd",  # Null byte
            ]

        successful_bypasses = []
        for payload in bypass_payloads[:30]:
            test_url = f"{url}?test={payload}"
            try:
                resp = await http.get(test_url, module="waf_detection")
                # If we get a 200 with a known-bad payload, the bypass worked
                if resp.status_code == 200:
                    successful_bypasses.append({
                        "payload": payload,
                        "status": resp.status_code,
                    })
            except Exception:
                continue

        if successful_bypasses:
            session.discovered.waf_detected["bypass_hints"] = [
                b["payload"] for b in successful_bypasses[:10]
            ]
            findings.append(Finding(
                title=f"WAF Bypass Possible ({waf_vendor})",
                severity=Severity.MEDIUM,
                category="waf_bypass",
                owasp_category="A05",
                description=(
                    f"{len(successful_bypasses)} WAF bypass techniques succeeded against {waf_vendor}. "
                    f"Encoding and obfuscation can circumvent the WAF protection. "
                    f"Successful bypasses: {', '.join(b['payload'][:50] for b in successful_bypasses[:5])}"
                ),
                remediation=(
                    "Implement application-level input validation in addition to WAF. "
                    "Update WAF rules to cover encoding bypass variants. "
                    "Consider using a WAF that normalizes input before rule evaluation."
                ),
                endpoint=url,
                evidence=[Evidence(
                    request_method="GET",
                    request_url=f"{url}?test={b['payload']}",
                    response_status=b["status"],
                    description=f"Bypass payload returned HTTP {b['status']}",
                ) for b in successful_bypasses[:5]],
                cwe_id="CWE-693",
                cvss_score=5.3,
                cvss_vector="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
            ))

        return findings
