export default {
  index: "Overview",
  "web-app-pentest": "Web app pentest (URL)",
  "spa-authenticated": "SPA + authenticated crawl",
  "api-pentest": "API + OpenAPI seed",
  "ai-target-provider-examples": "AI target provider examples",
  "llm-redteam-walkthrough": "LLM red team — walkthrough",
  "llm-ab-regression": "LLM A/B regression gate",
  "cloud-targets": "Cloud target registration",
  "android-apk-scanning": "Android APK scanning",
  "ios-ipa-scanning": "iOS IPA scanning",
  "browser-extension-scanning": "Browser extension scanning",
  "desktop-app-static-scanning": "Desktop app static scanning",
  "firmware-scanning": "Firmware scanning",
  "iot-device-scanning": "IoT device scanning",
  "monorepo-repo-scan": "Monorepo repo scan",
  "sca-supply-chain": "SCA + supply chain",
  "iac-cloud-hardening": "IaC + cloud hardening",
  "sbom-evidence": "SBOM as evidence",
  "audit-ready-bundle": "Audit-ready compliance bundle",
  "ci-gate": "CI gate (PR-blocking)",
};
