"""Ticketing system integrations for exporting findings.

Supported:
- GitHub Issues (via `gh` CLI — no extra deps)
- Jira (via REST API — requires JIRA_URL, JIRA_TOKEN, JIRA_PROJECT env vars)
"""

from __future__ import annotations

import json
import os
from typing import Any

from pencheff.core.findings import Finding


def _severity_to_github_label(severity: str) -> str:
    return {
        "critical": "severity: critical",
        "high": "severity: high",
        "medium": "severity: medium",
        "low": "severity: low",
        "info": "severity: info",
    }.get(severity.lower(), "severity: info")


def _format_github_body(finding: Finding, session_target: str) -> str:
    lines = [
        f"## {finding.title}",
        "",
        f"**Target:** `{session_target}`  ",
        f"**Endpoint:** `{finding.endpoint}`  ",
        f"**Parameter:** `{finding.parameter or 'N/A'}`  ",
        f"**CVSS Score:** {finding.cvss_score}  ",
        f"**CVSS Vector:** `{finding.cvss_vector or 'N/A'}`  ",
        f"**CWE:** {finding.cwe_id or 'N/A'}  ",
        f"**OWASP:** {finding.owasp_category}: {finding.owasp_name}  ",
        f"**Verification:** {finding.verification_status.value}  ",
        "",
        "### Description",
        finding.description,
        "",
        "### Remediation",
        finding.remediation,
    ]
    if finding.evidence:
        lines += ["", "### Evidence"]
        for ev in finding.evidence[:3]:
            lines.append(f"- `{ev.request_method} {ev.request_url}` → HTTP {ev.response_status}: {ev.description}")
    compliance = finding.compliance_mapping
    if compliance:
        lines += ["", "### Compliance Mapping"]
        for fw, controls in compliance.items():
            lines.append(f"- **{fw}:** {', '.join(controls)}")
    lines += ["", "---", "*Generated by [Pencheff](https://github.com/Magadha-IG/pencheff)*"]
    return "\n".join(lines)


async def export_to_github_issues(
    session: Any,
    repo: str,
    severities: list[str] | None = None,
    dry_run: bool = False,
    label_prefix: str = "security",
) -> dict[str, Any]:
    """Export verified/unverified findings to GitHub Issues via `gh` CLI.

    repo: owner/repo (e.g. 'myorg/myapp')
    severities: filter by severity (default: critical, high, medium)
    dry_run: preview without creating issues
    """
    from pencheff.core.tool_runner import tool_available, run_tool

    if not tool_available("gh"):
        return {
            "error": "GitHub CLI (gh) not installed. Install: https://cli.github.com/",
            "created": 0,
        }

    filter_sevs = set(s.lower() for s in (severities or ["critical", "high", "medium"]))
    findings = [
        f for f in session.findings.get_all()
        if f.severity.value in filter_sevs and not f.suppressed
    ]

    if not findings:
        return {"message": "No findings match the filter criteria.", "created": 0}

    created = []
    errors = []

    for f in findings:
        title = f"[Security] {f.severity.value.upper()} — {f.title}"
        body = _format_github_body(f, session.target.base_url)
        labels = [
            label_prefix,
            _severity_to_github_label(f.severity.value),
            f"owasp:{f.owasp_category}",
        ]

        if dry_run:
            created.append({"title": title, "labels": labels, "dry_run": True})
            continue

        args = [
            "gh", "issue", "create",
            "--repo", repo,
            "--title", title,
            "--body", body,
        ]
        for lbl in labels:
            args += ["--label", lbl]

        result = await run_tool(args, timeout=30.0)
        if result.success:
            # gh outputs the issue URL
            url = result.stdout.strip()
            created.append({"finding_id": f.id, "title": f.title, "issue_url": url})
        else:
            errors.append({
                "finding_id": f.id,
                "error": result.stderr[:200],
            })

    return {
        "repo": repo,
        "dry_run": dry_run,
        "created_count": len(created),
        "error_count": len(errors),
        "created": created,
        "errors": errors,
    }


async def export_to_jira(
    session: Any,
    project_key: str | None = None,
    severities: list[str] | None = None,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Export findings to Jira via REST API.

    Reads env vars: JIRA_URL, JIRA_TOKEN, JIRA_EMAIL, JIRA_PROJECT
    project_key overrides JIRA_PROJECT env var.
    """
    import httpx

    jira_url = os.environ.get("JIRA_URL", "").rstrip("/")
    jira_token = os.environ.get("JIRA_TOKEN", "")
    jira_email = os.environ.get("JIRA_EMAIL", "")
    project = project_key or os.environ.get("JIRA_PROJECT", "")

    if not jira_url:
        return {"error": "JIRA_URL environment variable not set."}
    if not jira_token:
        return {"error": "JIRA_TOKEN environment variable not set."}
    if not project:
        return {"error": "JIRA_PROJECT env var not set and project_key not provided."}

    filter_sevs = set(s.lower() for s in (severities or ["critical", "high", "medium"]))
    findings = [
        f for f in session.findings.get_all()
        if f.severity.value in filter_sevs and not f.suppressed
    ]

    if not findings:
        return {"message": "No findings match the filter criteria.", "created": 0}

    _PRIORITY_MAP = {
        "critical": "Highest",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "info": "Lowest",
    }
    _LABEL_MAP = {
        "critical": "security-critical",
        "high": "security-high",
        "medium": "security-medium",
        "low": "security-low",
        "info": "security-info",
    }

    auth = (jira_email, jira_token) if jira_email else None
    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json",
    }
    if not jira_email:
        headers["Authorization"] = f"Bearer {jira_token}"

    created = []
    errors = []

    async with httpx.AsyncClient(verify=False, timeout=30.0) as client:
        for f in findings:
            description_adf = {
                "version": 1,
                "type": "doc",
                "content": [
                    {"type": "paragraph", "content": [
                        {"type": "text", "text": f"Endpoint: {f.endpoint}"},
                    ]},
                    {"type": "paragraph", "content": [
                        {"type": "text", "text": f"CVSS: {f.cvss_score} — {f.cvss_vector or 'N/A'}"},
                    ]},
                    {"type": "paragraph", "content": [
                        {"type": "text", "text": f"CWE: {f.cwe_id or 'N/A'} | OWASP: {f.owasp_category}"},
                    ]},
                    {"type": "paragraph", "content": [
                        {"type": "text", "text": f.description},
                    ]},
                    {"type": "heading", "attrs": {"level": 3}, "content": [
                        {"type": "text", "text": "Remediation"},
                    ]},
                    {"type": "paragraph", "content": [
                        {"type": "text", "text": f.remediation},
                    ]},
                ],
            }

            payload = {
                "fields": {
                    "project": {"key": project},
                    "summary": f"[Security] {f.severity.value.upper()} — {f.title}",
                    "issuetype": {"name": "Bug"},
                    "priority": {"name": _PRIORITY_MAP.get(f.severity.value, "Medium")},
                    "labels": [_LABEL_MAP.get(f.severity.value, "security"), "pentest", "pencheff"],
                    "description": description_adf,
                },
            }

            if dry_run:
                created.append({"finding_id": f.id, "title": f.title, "dry_run": True, "payload": payload})
                continue

            try:
                kwargs: dict[str, Any] = {"json": payload, "headers": headers}
                if auth:
                    kwargs["auth"] = auth
                resp = await client.post(
                    f"{jira_url}/rest/api/3/issue",
                    **kwargs,
                )
                if resp.status_code in (200, 201):
                    data = resp.json()
                    created.append({
                        "finding_id": f.id,
                        "title": f.title,
                        "issue_key": data.get("key"),
                        "issue_url": f"{jira_url}/browse/{data.get('key')}",
                    })
                else:
                    errors.append({
                        "finding_id": f.id,
                        "status": resp.status_code,
                        "error": resp.text[:300],
                    })
            except Exception as e:
                errors.append({"finding_id": f.id, "error": str(e)})

    return {
        "project": project,
        "dry_run": dry_run,
        "created_count": len(created),
        "error_count": len(errors),
        "created": created,
        "errors": errors,
    }
