"""Persist LLM-generated explanation on findings

Adds a nullable JSONB ``ai_explanation`` column containing the four
auditor-facing sections generated by the LLM on first detail-page open:
``overview``, ``impact``, ``prevention``, ``scenarios``.

Revision ID: 0003
Revises: 0002
Create Date: 2026-04-18
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "findings",
        sa.Column("ai_explanation", postgresql.JSONB, nullable=True),
    )


def downgrade() -> None:
    op.drop_column("findings", "ai_explanation")
