export default {
  mcp: "MCP — drive from your IDE",
  dast: "DAST (web)",
  swarm: "AI agent swarm",
  "llm-redteam": "LLM red team",
  "ai-target-scanning": "AI targets (MCP/Agent/RAG/Voice)",
  sentry: "Sentry runtime guardrail",
  "agent-firewall": "Agent firewall",
  "runtime-traces": "Runtime traces",
  "memory-scanner": "Memory scanner",
  sca: "SCA (dependencies)",
  "advisory-ai": "Advisory AI enrichment",
  "auto-fix": "Auto-fix PRs",
  sbom: "SBOM generation",
  iac: "IaC scanning",
  "cloud-security": "Cloud security targets",
  container: "Container images",
  "admission-webhook": "Container registry + K8s admission",
  "api-discovery": "API discovery (runtime traffic)",
  "github-check-runs": "GitHub Check Run + SARIF",
  "partner-triage": "Partner pentest triage",
  "network-va": "Network VA",
  "active-directory": "Active Directory & Internal Network",
  "mobile-security": "Mobile Security",
  "browser-extension": "Browser Extension Security",
  "desktop-app": "Desktop App Security",
  "firmware-iot": "Firmware, IoT & OT Security",
  asm: "Attack Surface Management",
  proxy: "Intercepting proxy",
  fuzzer: "Parameter fuzzer",
  "passive-scan": "Passive scanner",
  reachability: "Reachability classifier",
  "epss-kev": "EPSS, KEV & SSVC",
  "threat-model": "Threat modeling (STRIDE / DREAD)",
  "security-lake": "Security Lake (OCSF / Iceberg)",
  "custom-llm-providers": "Custom LLM providers",
  "compliance-mapping": "Compliance mapping (per-scan)",
  observability: "Observability (OpenTelemetry)",
  dashboards: "Visual dashboards",
  "executive-dashboard": "Executive risk dashboard",
  "email-notifications": "Email notifications (Resend)",
  "ai-triage": "Triage 2.0",
  "findings-stream": "Unified findings stream",
  ide: "IDE extensions",
  authentication: "Authentication & sessions",
};
